### ISSUE TITLE
Integrate Permission2

### ISSUE THREAD

**Issue by Georges760** [asoul-sig/asouldocs#17]
As Peach is based on Macaron and xyproto/permissions2 has support to Macaron, would it be possible to have a Permission manager into Peach ? Maybe under the form of a new Extension that user can enable or disable...

I think I will give this a shot in the coming months, maybe we can do it together ?

**Comment by Unknwon** [comment]
Hi, this idea sounds very interesting!

But how do we integrate this permission system with existing documentation pages?

Similar way to [Basic Auth](https://peachdocs.org/docs/howto/protect_resources) support?
